export PROJECT = apniuniversity
IMPORT_PATH := github.com/HaziqAliSohail/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := sudo docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link apniuniversity-api-1:apniuniversity-api-1 \
    ${DEV_IMAGE}